### ISSUE TITLE
the meaning of diag?

### ISSUE THREAD

**Issue by morningsunflowers** [THU-KEG/KECG#2]
Your work benefit me a lot! And  i want to know the meaning of line 87 and 88 in `layers.py`.
```
if self.diag:
                h = torch.mul(input, self.w[i])
```
what is the `diag` means?Thanks a lot if you can give me explanations obout it.

**Comment by iamlockelightning** [comment]
Thank you for finding this work useful!

The `self.diag` flag controls whether to use the **Projection Constraint** (in Section 3.1), which restricts the projection matrix W to be a diagonal matrix. The torch.mul() will make use of the broadcast feature to do so.
