### ISSUE TITLE
关于实验结果和论文结果的问题

### ISSUE THREAD

**Issue by PrimaLuz** [THU-KEG/KECG#5]
你好，我在复现你的代码时发现结果分为“l2r”和“r2l”两个方向，论文里只有一个方向，比如DBP15Kzh-en。请问论文里的结果是否是实验中“l2r”+“r2l”求平均得来的吗？

**Comment by iamlockelightning** [comment]
Follow之前工作的指标（便于结果对比），加之篇幅限制，仅汇报了l2r的（https://github.com/THU-KEG/KECG/blob/master/log_kecg.txt#L1073）
